services:
  wobot-backend:
    build:
      context: .
      dockerfile: Dockerfile
      image: wobot-todo
    container_name: wobot-backend
    ports:
      - "8000:8000"
    command: ["bash","run.sh"]
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wobotai
    ports:
      - '3376:3306'